name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    name: Build on macOS
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.1"
    
    - name: Display Swift version
      run: swift --version
      
    - name: Build (Debug)
      run: swift build
      
    - name: Build (Release)
      run: swift build -c release
      
    - name: Create .app bundle
      run: make app
      
    - name: Verify .app bundle structure
      run: |
        if [ ! -d ".build/release/Cropper.app" ]; then
          echo "ERROR: .app bundle not created"
          exit 1
        fi
        if [ ! -f ".build/release/Cropper.app/Contents/MacOS/Cropper" ]; then
          echo "ERROR: Executable not found in bundle"
          exit 1
        fi
        if [ ! -f ".build/release/Cropper.app/Contents/Info.plist" ]; then
          echo "ERROR: Info.plist not found in bundle"
          exit 1
        fi
        echo "✅ App bundle structure verified"
      
    - name: Run executable (basic test)
      run: |
        echo "quit" | timeout 5 ./.build/debug/Cropper || true
    
    - name: Run XCUITests
      run: make test
